# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoWizard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoWizard

  target 'PhotoWizardTests' do
    pod 'MLImageSegmentationLibrary','~>2.0.4.300'
    # Pods for testing
  end

  target 'PhotoWizardUITests' do
    # Pods for testing
  end

end
